# Site settings
title: Abe Uchitelle
name: Abe Uchitelle
description: > # this means to ignore newlines
  The personal website of Abe Uchitelle, SVP of Business Development at DragonSearch. Check in to learn about sales, organizational development, and growth.
url: "http://abeuchitelle.com" # the base hostname & protocol for your site
twitter_username: abeuchitelle
linkedin_username: abeuchitelle

# Build settings
markdown: kramdown
permalink: "/:title/"
paginate: 10
paginate_path: "/:num"

gems:
  - jekyll-sitemap
